name: universal_vlm_jailbreak_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - menpo
  - defaults
dependencies:
  - python=3.10
  - transformers
  - accelerate
  - datasets
  - opencv-python-headless
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - sentencepiece
  - protobuf
  - omegaconf
  - iopath
  - opencv
  - webdataset
  - scipy
  - timm
  - matplotlib
  - seaborn
  - wandb
  - plotly
  - pip=23.3.1
  - pip:
    - decord
    - nvidia-htop
    - joblib