default_config = {
    "attack_kwargs": {
        "attack_name": "pgd",
        # "attack_name": "ssa_common_weakness",
        "batch_size": 1,
        # "clip_gradients": True,
        # "normalize_gradients": True,
        "generate_every_n_steps": 5,
        "step_size": 0.01,
        "total_steps": 10,
    },
    "image_kwargs": {
        "image_size": 336,
        "image_initialization": "random",
    },
    "models_to_attack": "{'llava-v1p5-vicuna7b'}",
    "models_to_eval": "{'llava-v1p5-vicuna7b'}",
    # "models_to_attack": "{'llava-v1p6-mistral7b'}",
    # "models_to_eval": "{'llava-v1p6-mistral7b'}",
    # "models_to_attack": "{'llava-v1.6-vicuna13b'}",
    # "models_to_eval": "{'llava-v1.6-vicuna13b'}",
    # "models_to_attack": "{'prism-dinosiglip+7b'}",
    # "models_to_eval": "{'prism-dinosiglip+7b'}",
    # "models_to_attack": "{'llava-v1p5-vicuna7b', 'llava-v1p6-mistral7b'}",
    # "models_to_eval": "{'llava-v1p5-vicuna7b', 'llava-v1p6-mistral7b'}",
    "model_generation_kwargs": {
        "llava-v1p6-mistral7b": {
            "temperature": 0.1,
            "top_p": 0.9,
            "max_new_tokens": 100,
            "min_new_tokens": 5,
        },
        "llava-v1p5-vicuna7b": {
            "temperature": 0.1,
            "top_p": 0.9,
            "max_new_tokens": 100,
            "min_new_tokens": 5,
        },
        "llava-v1p6-vicuna7b": {
            "temperature": 0.1,
            "top_p": 0.9,
            "max_new_tokens": 100,
            "min_new_tokens": 5,
        },
        "llava-v1p6-vicuna13b": {
            "temperature": 0.1,
            "top_p": 0.9,
            "max_new_tokens": 100,
            "min_new_tokens": 5,
            "use_cache": False,
            "cache_position": None,
        },
        "prism-dinosiglip+7b": {
            "temperature": 0.1,
            "top_p": 0.9,
            "max_new_tokens": 100,
            "min_new_tokens": 5,
        },
    },
    # "models_to_eval": "{'instructblip2-vicuna-7b'}",
    "prompt_and_targets_kwargs": {
        "dataset_train": "rylan_anthropic_hhh",
        "dataset_test": "advbench",
        "n_unique_prompts_and_targets": -1,  # -1 means use all prompts and targets.
    },
    # "prompts_and_targets": "advbench",
    "seed": 0,
}
