default_attack_config = {
    # "compile": True,
    "compile": False,
    "data": {
        "dataset": "advbench",
        "batch_size": 3,
        "num_workers": 1,
        "split": "train",
    },
    "image_kwargs": {
        "image_size": 512,
        "image_initialization": "random",
    },
    "lightning_kwargs": {
        "accumulate_grad_batches": 6,
        "gradient_clip_val": 10.0,
        # "limit_train_batches": 1.0,
        "limit_train_batches": 0.05,  # Fast debugging.
        "log_loss_every_n_steps": 1,
        "log_image_every_n_steps": 1000,
        "precision": "bf16-mixed",
        # "precision": "bf16-true",
    },
    # "models_to_attack": "{'llava-v1p5-vicuna7b'}",
    # "models_to_attack": "{'llava-v1p6-mistral7b'}",
    # "models_to_attack": "{'llava-v1.6-vicuna13b'}",
    # "models_to_attack": "{'prism-reproduction-llava-v15+7b'}",
    # "models_to_attack": "{'prism-reproduction-llava-v15+13b'}",
    # "models_to_attack": "{'prism-dinosiglip+7b'}",
    "models_to_attack": "{'prism-clip+7b'}",
    # "models_to_attack": "{'prism-reproduction-llava-v15+7b', 'prism-clip+7b'}",
    # "models_to_attack": "{'prism-clip+7b', 'prism-siglip+7b'}",
    # "models_to_attack": "{'prism-dinosiglip+7b'}",
    # "models_to_attack": "{'llava-v1p5-vicuna7b', 'llava-v1p6-mistral7b'}",
    "model_generation_kwargs": {},
    "n_grad_steps": 2500,
    "n_generations": 10,
    "optimization": {
        "eps": 1e-4,
        "learning_rate": 0.001,
        "momentum": 0.0,
        # "momentum": 0.9,
        # "optimizer": "adam",
        "optimizer": "sgd",
        "weight_decay": 0.00001,
    },
    "seed": 0,
}


default_eval_config = {
    "data": {
        "num_workers": 1,
        "batch_size": 1,
        "dataset": "rylan_anthropic_hhh",
        "split": "eval",
    },
    "lightning_kwargs": {
        "log_loss_every_n_steps": 1,
        "precision": "bf16-mixed",
    },
    # "model_to_eval": "{'prism-reproduction-llava-v15+7b'}",
    "model_to_eval": "{'prism-clip+7b'}",
    # "model_to_eval": "{'prism-reproduction-llava-v15+7b', 'prism-reproduction-llava-v15+13b'}",
    "model_generation_kwargs": {
        # "prism-reproduction-llava-v15+7b": {
        #     "temperature": 0.1,
        #     "top_p": 0.9,
        #     "max_new_tokens": 100,
        #     "min_new_tokens": 5,
        # },
        # "prism-reproduction-llava-v15+13b": {
        #     "temperature": 0.1,
        #     "top_p": 0.9,
        #     "max_new_tokens": 100,
        #     "min_new_tokens": 5,
        # },
        # "prism-clip+7b": {
        #     "temperature": 0.1,
        #     "top_p": 0.9,
        #     "max_new_tokens": 100,
        #     "min_new_tokens": 5,
        # },
        # "prism-siglip+7b": {
        #     "temperature": 0.1,
        #     "top_p": 0.9,
        #     "max_new_tokens": 100,
        #     "min_new_tokens": 5,
        # },
        # "prism-dinosiglip+7b": {
        #     "temperature": 0.1,
        #     "top_p": 0.9,
        #     "max_new_tokens": 100,
        #     "min_new_tokens": 5,
        # },
        # "llava-lvis4v-lrv+7b": {
        #     "temperature": 0.1,
        #     "top_p": 0.9,
        #     "max_new_tokens": 100,
        #     "min_new_tokens": 5,
        # },
    },
    "n_generations": 5,
    "seed": 0,
    "wandb_run_id": "m4s17qlw",
    # "wandb_sweep_id": "yvqszl4d",
}
